### ISSUE TITLE
Bug: map() predicates are called multiple times

### ISSUE THREAD

**Issue by florianschieder** [mifeet/pyfluent-iterables#2]
Minimal reproducible example: Be `step(n)` a function returning `n**2`  and printing `n`

`>>> def step(n):`
`...     print(n)`
`...     return n ** 2`
`... `

Classical list comprehension (same goes for `list(map(...))`) works as intended:
`>>> [step(n) for n in [1, 2, 3, 4]]`
`1`
`2`
`3`
`4`
`[1, 4, 9, 16]`

`fluent(...).map(...).to_list()` causes the predicate `step` to be called twice:

`>>> fluent([1, 2, 3, 4]).map(step).to_list()`
`1`
`2`
`3`
`4`
`1`
`2`
`3`
`4`
`[1, 4, 9, 16]`

The return value is the same but I think this is not the desired behaviour to call the predicate multiple times.

**Comment by feynmanix** [comment]
You're right, thanks for reporting! Hopefully fixed in [v1.2.0](https://github.com/mifeet/pyfluent-iterables/releases/tag/1.2.0)
