### ISSUE TITLE
Please consider adding functions from more-itertools

### ISSUE THREAD

**Issue by OlegAlexander** [mifeet/pyfluent-iterables#3]
Hello and thank you for creating `pyfluent-iterables`! IMO, this is the cleanest and well-maintained fluent api Python library among its competitors. 

Have you considered adding functions from [`more-itertools`](https://more-itertools.readthedocs.io/en/stable/)? This is a well-maintained library with many useful iterator functions. (Perhaps too many!) I'm not suggesting that you should add all of them, but some, like `chunked`, `transpose`, and `windowed` could be very useful.

**Comment by feynmanix** [comment]
Hi, thank you for the feedback!
Some functionality from more-itertools may already be there (e.g., `chunked` is called [grouped()](https://github.com/mifeet/pyfluent-iterables/blob/f8d983ea036bb958ee2b0a55597b973d47a4d2a7/pyfluent_iterables/fluent.py#L237)) but there are way more things in more-itertools than I think would fit here.

However, perhaps we could extend pyfluent-iterables to be extensible with other libraries like more-itertools? E.g., something like `fluent_of(1,2,3).apply(more_itertools.windowed, 2)`? Not sure how tricky it would be to preserve type safety, but it should be possible to implement something like this in principle.

**Comment by feynmanix** [comment]
See https://github.com/mifeet/pyfluent-iterables/releases/tag/2.0.0
